# Generated by Django 2.1.2 on 2019-02-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwshortener', '0003_link_clicks'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['slug'], name='kwshortener_slug_7d0499_idx'),
        ),
    ]
